# Generated by Django 5.2.4 on 2025-07-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('etat_civil', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Union libre', 'Union libre')], max_length=20)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('commune', models.CharField(choices=[('Barumbu', 'Barumbu'), ('Bumbu', 'Bumbu'), ('Kalamu', 'Kalamu'), ('Kasa-Vubu', 'Kasa-Vubu'), ('Kinshasa', 'Kinshasa'), ('Kintambo', 'Kintambo'), ('Lingwala', 'Lingwala'), ('Gombe', 'Gombe'), ('Ngaliema', 'Ngaliema'), ('Mont Ngafula', 'Mont Ngafula'), ('Lemba', 'Lemba'), ('Ngaba', 'Ngaba'), ('Matete', 'Matete'), ('Kisenso', 'Kisenso'), ('Kimbanseke', 'Kimbanseke'), ('Nsele', 'Nsele'), ('Maluku', 'Maluku'), ('Masina', 'Masina'), ('Ndjili', 'Ndjili'), ('N’djili', 'N’djili'), ('Limete', 'Limete'), ('Selembao', 'Selembao'), ('Makala', 'Makala'), ('Kasavubu', 'Kasavubu'), ('Bandalungwa', 'Bandalungwa')], max_length=100, null=True)),
                ('quartier', models.CharField(max_length=100, null=True)),
                ('avenue', models.CharField(max_length=100, null=True)),
                ('cnom', models.CharField(max_length=100)),
                ('langues', models.JSONField(blank=True, default=list, null=True)),
                ('specialite', models.CharField(choices=[('Médecine générale', 'Médecine générale'), ('Pédiatrie', 'Pédiatrie'), ('Gynécologie-obstétrique', 'Gynécologie-obstétrique'), ('Chirurgie générale', 'Chirurgie générale'), ('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Neurologie', 'Neurologie'), ('Psychiatrie', 'Psychiatrie'), ('Ophtalmologie', 'Ophtalmologie'), ('ORL (Oto-rhino-laryngologie)', 'ORL (Oto-rhino-laryngologie)'), ('Urologie', 'Urologie'), ('Orthopédie', 'Orthopédie'), ('Gastro-entérologie', 'Gastro-entérologie'), ('Endocrinologie', 'Endocrinologie'), ('Hématologie', 'Hématologie'), ('Néphrologie', 'Néphrologie'), ('Oncologie', 'Oncologie'), ('Rhumatologie', 'Rhumatologie'), ('Médecine interne', 'Médecine interne'), ('Médecine d’urgence', 'Médecine d’urgence'), ('Anesthésie-Réanimation', 'Anesthésie-Réanimation'), ('Radiologie', 'Radiologie'), ('Médecine tropicale', 'Médecine tropicale'), ('Santé publique', 'Santé publique'), ('Médecine du travail', 'Médecine du travail'), ('Médecine légale', 'Médecine légale'), ('Autre', 'Autre')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('etat_civil', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('commune', models.CharField(choices=[('Barumbu', 'Barumbu'), ('Bumbu', 'Bumbu'), ('Kalamu', 'Kalamu'), ('Kasa-Vubu', 'Kasa-Vubu'), ('Kinshasa', 'Kinshasa'), ('Kintambo', 'Kintambo'), ('Lingwala', 'Lingwala'), ('Gombe', 'Gombe'), ('Ngaliema', 'Ngaliema'), ('Mont Ngafula', 'Mont Ngafula'), ('Lemba', 'Lemba'), ('Ngaba', 'Ngaba'), ('Matete', 'Matete'), ('Kisenso', 'Kisenso'), ('Kimbanseke', 'Kimbanseke'), ('Nsele', 'Nsele'), ('Maluku', 'Maluku'), ('Masina', 'Masina'), ('Ndjili', 'Ndjili'), ('N’djili', 'N’djili'), ('Limete', 'Limete'), ('Selembao', 'Selembao'), ('Makala', 'Makala'), ('Kasavubu', 'Kasavubu'), ('Bandalungwa', 'Bandalungwa')], max_length=100, null=True)),
                ('quartier', models.CharField(max_length=100, null=True)),
                ('avenue', models.CharField(max_length=100, null=True)),
                ('langue_preferee', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('assureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobiko.assureur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobiko.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SessionDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobiko.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobiko.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emetteur_bot', models.BooleanField(default=False)),
                ('emetteur_medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobiko.medecin')),
                ('emetteur_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobiko.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobiko.sessiondiscussion')),
            ],
        ),
    ]
