# Generated by Django 5.2.4 on 2025-07-14 21:22

import lobiko.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobiko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='cnom',
            field=models.CharField(max_length=100, verbose_name='Numéro CNOM'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='langues',
            field=models.JSONField(blank=True, default=list, null=True, validators=[lobiko.models.validate_langues]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='langue_preferee',
            field=models.JSONField(blank=True, default=list, null=True, validators=[lobiko.models.validate_langues]),
        ),
    ]
