# Generated by Django 5.2.4 on 2025-07-11 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobiko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emetteur',
        ),
        migrations.AddField(
            model_name='message',
            name='emetteur_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='emetteur_medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobiko.medecin'),
        ),
        migrations.AddField(
            model_name='message',
            name='emetteur_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobiko.patient'),
        ),
    ]
