# Generated by Django 5.2.4 on 2025-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobiko', '0002_alter_medecin_cnom_alter_medecin_langues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf'), ('Union libre', 'Union libre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf'), ('Union libre', 'Union libre')], max_length=20),
        ),
    ]
