# Generated by Django 5.2.4 on 2025-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobiko', '0003_alter_medecin_etat_civil_alter_patient_etat_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Union libre', 'Union libre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Union libre', 'Union libre')], max_length=20),
        ),
    ]
