# Generated by Django 5.2.4 on 2025-07-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobiko', '0004_alter_medecin_etat_civil_alter_patient_etat_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('other', 'Autre')], max_length=10)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emetteur_type', models.CharField(choices=[('PATIENT', 'Patient'), ('MEDECIN', 'Médecin'), ('BOT', 'Bot')], max_length=10)),
                ('emetteur_id', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='lobiko.sessiondiscussion')),
            ],
            options={
                'verbose_name': 'Fichier média',
                'verbose_name_plural': 'Fichiers médias',
            },
        ),
    ]
